import Header from '../components/header.js'
import Footer from '../components/footer.js'
import Link from 'next/link'

const box = {
    float: 'left',
    width: '32%',
    height: '10em',
    padding: '0.4em',
}

const Subsystem = (props) => (
    <div style={ box }>
        <h3>{props.title}</h3>
        <p>{props.desc}</p>
    </div>
)

const buttonStyle = {
    textAlign: 'center',
    padding: '0em 24em 0em 24em',
}

const linkStyle = {
    backgroundColor: '#222',
    color: '#fff',
    fontSize: '15px',
    boxShadow: '0em 0.7em 1em 0.3em #ccc',
    padding: '1em 2em 1em 2em',
    textDecoration: 'none',
    border: '0px solid',
    borderRadius: '0.5em',
    transition: '0.5s ease',
    width: '5em',
    margin: '4em',
    fontWeight: 'bold',
}

const Button = (props) => (
    <div style={buttonStyle}>
        <Link href={`{$props.link}`}><a style={linkStyle}>{props.label}</a></Link>
    </div>
)
const Index = () => (
    <div className="container">
        <Header />
        <div className="body">
            <h1>Fly to the Zenith</h1>
            <div className="info">
                <p>
                    Project Jatayu is the Autonomous Unmanned Aerial Vehicle
                    team of RVCE. The project's aim is to build and test a <b>fully autonomous piloting system</b> which has the potential to be
                    deployed.
            </p>
            </div>

            <br />
            <br />
            <Button link='/about' label='LEARN MORE' />
            <br />
            <br />
            <div className="separator">
                <span></span>
            </div>
            <br />
            <br />

            <div className="info">
                <h4>OUR APPROACH</h4>
                <h2>Divide and Conquer</h2>
                <p>
                    Project Jatayu is an inter-disciplinary Autonomous UAV team, 
                    comprising of various subsystems which work together, to complete out the tasks.
                </p>
            </div>
            <div className="subs clearfix">
                <Subsystem title="Aerodynamics"       desc ="The science with which a drone flies, and all the physics involved in it, lies in the hands of Aerodynamics Subsystem." />
                <Subsystem title="Propulsion"         desc ="The science and action of driving a drone in the air, is handled by the Propulsion Subsystem." />
                <Subsystem title="Computer Vision"    desc ="This subsystem is responsible for handling the Image Analysis and Detection tasks, for the imagery generated by the drones." />
            </div>
            <div className="subs clearfix">
                <Subsystem title="Image Transmission" desc ="This subsystem works closely with Image Processing team and its job is to transfer the images and other related data from drone to base computer." />
                <Subsystem title="Autonomy"           desc ="Autonomy is an important part of the mission process, as the drone should be autonomous." />
                <Subsystem title="Structures"         desc ="Handled by Mechanical and Aerospace engineers, this subsystem is responsible for structural integrity of the drone." />
            </div>

            <br />
            <br />
            <Button link='/subsystems' label='SUBSYSTEMS' />
            <br />
            <br />
            
            <style jsx>{`
                body {
                    height: 100%
                    margin: 0;
                    padding: 0px;
                }
                .container {
                    min-height: 100%;
                    position: relative;
                    margin: 0;
                    padding: 0;
                }
                .body {
                    font-size: 18px;
                    padding: 4em 10em 2em 10em;
                    font-family: "Inter"
                }
                h1, h2, h3, h4 {
                    text-align: center;
                    font-size: 5em;
                    font-vairant: bold;
                } 
                h2 {
                    font-size: 3em;
                } 
                h3 {
                    font-size: 2em;
                }
                h4 {
                    font-size: 1em;
                }
                .separator {
                    margin: 1em 0em;
                    border-top: 0.5px solid #dedede;
                }
                .info {
                    text-align: center;
                    padding: 0em 24em 0em 24em;
                }
                .clearfix::after {
                    content: "";
                    display: table;
                    clear: both;
                }
                subs {
                    width: 100%;
                    text-align: right;
                    margin: 0;
                    padding: 0;
                }
                    `}</style>
            </div>
            <Footer />
        </div>
)

export default Index
