import Header from '../components/header.js';
import Footer from '../components/footer.js';
import Link from 'next/link';

import '../styles/Button.css';
import '../styles/Headings.css';
import '../styles/Separator.css';
import '../styles/Responsive.css';

const box = {
    float: 'left',
    width: '32%',
    height: '10rem',
    margin: '0.5rem',
    padding: '0.4rem',
}

const Subsystem = (props) => (
    <div className="col-3">
        <h3 style={ {textAlign: 'center'} }>{props.title}</h3>
        <p>{props.desc}</p>
    </div>
)

const Button = (props) => (
    <div className="buttonStyle">
        <Link href={`${props.link}`}><a className="linkStyle">{props.label}</a></Link>
    </div>
)

const Index = () => (
    <div className="container">
        <Header />
        <div className="body">
            <div className="row">
                <h1 style={{ textAlign: 'center', fontSize: '5rem' }}>Fly to the Zenith</h1>
            </div>
            <div className="row">
                <div className="col-3"></div>
                <div className="center col-6">
                    <p>
                        Project Jatayu is the Autonomous Unmanned Aerial Vehicle
                        team of RVCE. The project's aim is to build and test a <b>fully autonomous piloting system</b> which has the potential to be
                        deployed.
                    </p>
                </div>
            </div>

            <br />
            <br />
            <div className="row">
                <div className="col-4"></div>
                <div className="col-4">
                    <Button link='/about' label='LEARN MORE' />
                </div>
            </div>
            <br />
            <br />
            <div className="separator">
                <span></span>
            </div>
            <br />
            <br />

            <div className="row">
                <div className="col-3"></div>
                <div className="col-6">
                    <div className="center">
                        <h4>OUR APPROACH</h4>
                        <h2>Divide and Conquer</h2>
                        <p>
                            Project Jatayu is an inter-disciplinary Autonomous UAV team, 
                            comprising of various subsystems which work together, to complete out the tasks.
                        </p>
                    </div>
                </div>
            </div>

            <div className="row justify">
                <div className="col-1-5"></div>
                <Subsystem title="Aerodynamics"       desc ="The science with which a drone flies, and all the physics involved in it, lies in the hands of Aerodynamics Subsystem." />
                <Subsystem title="Propulsion"         desc ="The science and action of driving a drone in the air, is handled by the Propulsion Subsystem." />
                <Subsystem title="Computer Vision"    desc ="This subsystem is responsible for handling the Image Analysis and Detection tasks, for the imagery generated by the drones." />
            </div>
            <div className="row justify">
                <div className="col-1-5"></div>
                <Subsystem title="Image Transmission" desc ="This subsystem works closely with Image Processing team and its job is to transfer the images and other related data from drone to base computer." />
                <Subsystem title="Autonomy"           desc ="Autonomy is an important part of the mission process, as the drone should be autonomous." />
                <Subsystem title="Structures"         desc ="Handled by Mechanical and Aerospace engineers, this subsystem is responsible for structural integrity of the drone." />
            </div>

    <br />
    <br />
    <div className="row">
        <div className="col-4"></div>
        <div className="col-4">
            <Button link='/subsystems' label='SUBSYSTEMS' />
        </div>
    </div>
    <br />
    <br />

    <style jsx>{`
                html {
                    font-size: 16px;
                }
                body {
                    height: 100%
                    margin: 0;
                    padding: 0px;
                }
                .container {
                    min-height: 100%;
                    position: relative;
                    margin: 0;
                    padding: 0;
                }
                .body {
                    font-size: 18px;
                    padding: 4rem 0rem 2rem 0rem;
                    font-family: "Inter"
                }
                .info {
                    padding: 0rem 18rem 0rem 18rem;
                }
                .subtitle {
                    padding: 0rem 25rem 0rem 25rem;
                }
                .center {
                    text-align: center;
                }
                .justify {
                    text-align: justify;
                }
                .clearfix::after {
                    content: "";
                    display: table;
                    clear: both;
                }
                subs {
                    width: 100%;
                    margin: 0;
                    padding: 0;
                }
                    `}</style>
            </div>
            <Footer />
        </div>
)

export default Index
