import Header from '../components/header.js';
import Footer from '../components/footer.js';
import Link from 'next/link';

import '../styles/Headings.css'
import '../styles/Card.css'
import '../styles/Separator.css'
import '../styles/Responsive.css'

function get_cols() {
    return [
        { title: "Aerodynamics"       , img: "/static/vecs/001-propeller.svg"  ,content: "The science with which a drone flies, and all the physics involved in it, lies in the hands of Aerodynamics Subsystem. "} ,
        { title: "Propulsion"         , img: "/static/vecs/015-startup.svg"  ,content: "The science and action of driving a drone in the air, is handled by the Propulsion Subsystem."} ,
        { title: "Computer Vision"    , img: "/static/vecs/005-viewfinder.svg"  ,content: "This subsystem is responsible for handling the Image Analysis and Detection tasks, for the imagery generated by the drones."} ,
        { title: "Image Transmission" , img: "/static/vecs/008-antenna.svg"  ,content: "This subsystem works closely with Image Processing team and its job is to transfer the images and other related data from drone to base computer."} ,
        { title: "Autonomy"           , img: "/static/vecs/009-navigation.svg"  ,content: "Autonomy is an important part of the mission process, as the drone should be autonomous."} ,
        { title: "Structures"         , img: "/static/vecs/011-drone.svg"  ,content: "Handled by Mechanical and Aerospace engineers, this subsystem is responsible for structural integrity of the drone."} ,
    ]
}

function Sub (props) {
    if (props.idx%2 === 0) {
        return (
            <div className="row">
                <div className="col-2"></div>
                <div className="col-4">
                    <h3>{props.title}</h3>
                    <br />
                    <br />
                    <p>{props.content}</p>
                </div>
                <div className="col-4">
                    <img src={`${props.img}`}/>
                </div>
            </div>
        )
    } else {
        return (
            <div className="row">
                <div className="col-2"></div>
                <div className="col-4">
                    <img src={`${props.img}`}/>
                </div>
                <div className="col-4">
                    <h3>{props.title}</h3>
                    <br />
                    <br />
                    <p>{props.content}</p>
                </div>
            </div>
        )
    }
}

const Subsystems = () => (
    <div className="container">
        <Header />
        <div className="body">
            <div className="row">
                <div className="col-12 center">
                    <h2>Subsystems</h2>
                </div>
            </div>
            {
                get_cols().map((col, idx) => (
                    <div>
                        <Sub title={col.title} content={col.content} img={col.img} idx={idx}></Sub>
                        <br />
                        <br />
                        <br />

                    </div>
                ))
            }
            <style>{`
                .inrow {
                    display: flex;
                }
                .incol-1 {
                    flex: 20%;
                }
                .incol-2 {
                     flex: 80%;
                }
                html {
                    font-size: 16px;
                }
                body {
                    height: 100%
                    margin: 0;
                    padding: 0px;
                }
                .container {
                    min-height: 100%;
                    position: relative;
                    margin: 0;
                    padding: 0;
                }
                .center {
                    text-align: center;
                }
                .body {
                    font-size: 18px;
                    padding: 4rem 0rem 2rem 0rem;
                    font-family: "Inter"
                }
                .contained {
                  position: absolute;
                  top: 0;
                  left: 0;
                  right: 0;
                  bottom: 0;
                }
                .wrapper {
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100%;
                }
                img {
                    display: block;
                    margin: auto;
                    width: 40%;
                    border-radius: 1rem;
                }
                `}</style>
        </div>
        <Footer />
    </div>
)

export default Subsystems
